# -*- coding: utf-8 -*-
"""EECS240_Proj2_Prob2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hsGn78ELEjzLS9NZLzpEXoCz4EJsdoMb
"""

import numpy
import matplotlib.pyplot as plt
import math

# set up the pi variable
pi = math.pi
# generate an array of zeros
X = numpy.zeros(100)
# use a for loop to generate the data
for i in range(99):
    Θ = numpy.random.uniform(-pi, pi, 1)
    X[i] = math.cos(0.2*pi*i+Θ)
# plot the data
plt.plot(X, 'o')
plt.show()